# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      "Env": "env-renanzin-27-03-2024"
"Region": "us-east-1"
"managed_by": "RenanCoradini/Terraform/Terragrunt"

    }
  } 
}
